FROM almalinux:9
ENV course="DevOps with AWS"\
    trainer="sivakumar reddy"\
    duration="120 hrs"
ARG USERNAME=Ravindra  
RUN echo "Hello user : ${USERNAME}" > /tmp/devops.txt
CMD ["sleep", "100"]   