FROM almalinux:9
ENV course="DevOps with AWS"\
    trainer="sivakumar reddy"\
    duration="120 hrs"
ARG ${username:-someuser}    
RUN echo "Hello ${username}" > /tmp/devops.txt
CMD ["sleep", "100"]   